name: aws-eb-deploy
env:
  AWS_REGION:          eu-central-1


on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Terraform init
        run: |
          ls -la \
          terraform init eu-central-1/dev \
          terraform plan eu-central-1/dev
